name: .NET

on:
  push:
  pull_request:
    
env:
  config: Release
  disable_test_parallelization: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20


    steps:
    - uses: actions/checkout@v2

    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Test
      run: dotnet run -p build/build.csproj -- compile

    - name: Core Tests
      run: dotnet test --no-build --no-restore src/Testing/CoreTests/CoreTests.csproj --logger "console;verbosity=detailed"
        
    - name: Persistence Tests
      run: dotnet test --no-build --no-restore src/Persistence/PersistenceTests/PersistenceTests.csproj --logger "console;verbosity=detailed"
        
    - name: RabbitMQ Tests
      run: dotnet test --no-build --no-restore src/Transports/Wolverine.RabbitMQ.Tests/Wolverine.RabbitMQ.Tests.csproj --logger "console;verbosity=detailed"
        
    - name: Pulsar Tests
      run: dotnet test --no-build --no-restore src/Transports/Wolverine.Pulsar.Tests/Wolverine.Pulsar.Tests.csproj --logger "console;verbosity=detailed"
